#!/bin/bash
set -e

# Create databases and users
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    -- Metadata database
    CREATE DATABASE $METADATA_DATABASE_NAME;
    CREATE USER $METADATA_DATABASE_USERNAME WITH PASSWORD '$METADATA_DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $METADATA_DATABASE_NAME TO $METADATA_DATABASE_USERNAME;

    -- Celery database
    CREATE DATABASE $CELERY_BACKEND_NAME;
    CREATE USER $CELERY_BACKEND_USERNAME WITH PASSWORD '$CELERY_BACKEND_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $CELERY_BACKEND_NAME TO $CELERY_BACKEND_USERNAME;

    -- ELT database
    CREATE DATABASE $ELT_DATABASE_NAME;
    CREATE USER $ELT_DATABASE_USERNAME WITH PASSWORD '$ELT_DATABASE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $ELT_DATABASE_NAME TO $ELT_DATABASE_USERNAME;
EOSQL